##Proxy, LoadBalancer, and Logger hostname and ports Followed by slice of Backend Servers.
proxyhost : localhost
proxyport : 6060
loadhost: localhost
loadport: 6061
loghost: localhost
logport: 3333
servers:
    - hostname: localhost
      port: 7777
    - hostname: localhost
      port: 8888
    - hostname: localhost
      port: 9999