apiVersion: apps/v1
kind: Deployment
metadata:
    name: collider-deployment
spec:
    selector:
        matchLabels:
            app: collider
    replicas: 1
    template:
        metadata:
            labels:
                app: collider
        spec:
            containers:
            - name: collider
              image: gophersuits/collider:0.4
              ports:
              - containerPort: 8080
            - name: dic
              image: gophersuits/dic:latest
              ports:
              - containerPort: 5432
---
kind: Service
apiVersion: v1
metadata:
    name: collider-service
spec:
    selector:
        app: collider
    ports:
    - name: collider
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
    - name: dic
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 31000
    type: NodePort